// Quote/order numbers used to be generated by reading the most recent row,
// stripping the prefix, incrementing by 1, and inserting. That's not atomic:
// two reps saving at the same moment both saw the same "last number", both
// computed the same "next", and the second insert hit
//   23505 duplicate key value violates unique constraint
// — surfacing as "שמירת ההצעה נכשלה" with no recovery.
//
// `nextSequentialNumber` finds the actual MAX across a recent batch (so a
// row with a higher number created earlier still wins), and the wrapper
// `createWithSequentialNumber` retries on unique-violation, bumping the
// candidate each attempt until either it lands or we hit `maxAttempts`.
//
// This is a client-side mitigation; a server-side sequence/RPC is the
// proper long-term fix but needs a DB migration. The retry loop handles
// both concurrent saves and out-of-order insertions safely.

const UNIQUE_VIOLATION_CODES = new Set(['23505']);

function isUniqueViolation(err) {
  if (!err) return false;
  if (err.code && UNIQUE_VIOLATION_CODES.has(String(err.code))) return true;
  // Some wrappers expose the PG code as a sub-property — check there too
  // so a wrapped PostgrestError doesn't slip past us.
  const nestedCode = err.cause?.code || err.error?.code || err.originalError?.code;
  if (nestedCode && UNIQUE_VIOLATION_CODES.has(String(nestedCode))) return true;
  const text = [err.message, err.details, err.hint, err.cause?.message, err.error?.message]
    .filter(Boolean)
    .join(' ')
    .toLowerCase();
  return text.includes('duplicate key') || text.includes('unique constraint') || text.includes('23505');
}

function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Compute the next prefixed number ("Q1234", "ORD10001", …) by scanning the
 * recent rows and taking MAX of the numeric tail.
 *
 * @param {Array<object>} recentRows  Recently-fetched rows that carry the field.
 * @param {string} field              Field name on each row (e.g. 'quote_number').
 * @param {string} prefix             Prefix to strip / re-attach (e.g. 'Q').
 * @param {number} startingValue      Value to use when the table is empty.
 * @param {number} bump               Extra amount to add on top (used by retries).
 */
export function nextSequentialNumber(recentRows, field, prefix, startingValue, bump = 0) {
  const max = (recentRows || [])
    .map((row) => parseInt(String(row?.[field] || '').replace(prefix, ''), 10))
    .filter((n) => Number.isFinite(n))
    .reduce((m, n) => (n > m ? n : m), startingValue - 1);
  return `${prefix}${max + 1 + bump}`;
}

/**
 * Create a row whose `numberField` (e.g. quote_number / order_number) is
 * generated by `nextSequentialNumber`, with retry-on-unique-violation.
 *
 * Retry strategy: each attempt bumps the candidate by `attempt * attempt`
 * (1, 4, 9, 16, …) instead of linearly so heavy contention converges fast,
 * and waits a small jittered backoff so concurrent callers don't sync-step
 * onto the same fresh number.
 *
 * @param {object}   options
 * @param {object}   options.entity         base44 entity wrapper (must support .list and .create).
 * @param {string}   options.numberField    Field name to set on the new row.
 * @param {string}   options.prefix         Prefix for the generated number.
 * @param {number}   options.startingValue  Value to start from when the table is empty.
 * @param {number}  [options.scanRecent=50] How many recent rows to scan for the current MAX.
 * @param {number}  [options.maxAttempts=10] Cap retries so we don't hammer the DB.
 * @param {(numberValue: string) => object} options.buildPayload
 *        Returns the payload for entity.create, given the candidate number.
 */
export async function createWithSequentialNumber({
  entity,
  numberField,
  prefix,
  startingValue,
  scanRecent = 50,
  maxAttempts = 10,
  buildPayload,
}) {
  let lastErr = null;
  for (let attempt = 0; attempt < maxAttempts; attempt += 1) {
    if (attempt > 0) {
      // Jittered backoff: 50–200ms × attempt. Gives any concurrent insert
      // time to land so our re-fetch sees the new MAX.
      const backoff = (50 + Math.floor(Math.random() * 150)) * attempt;
      await delay(backoff);
    }
    const recent = await entity.list('-created_date', scanRecent);
    // Quadratic bump (attempt²) so a heavily-contested table converges in a
    // handful of tries instead of marching one number at a time. Sacrifices
    // contiguous numbering under contention, which is acceptable.
    const candidate = nextSequentialNumber(recent, numberField, prefix, startingValue, attempt * attempt);
    try {
      const created = await entity.create(buildPayload(candidate));
      if (attempt > 0) {
        // eslint-disable-next-line no-console
        console.info(`[sequentialNumber] ${prefix}* allocated as ${candidate} on attempt ${attempt + 1}`);
      }
      return created;
    } catch (err) {
      lastErr = err;
      if (isUniqueViolation(err)) {
        // eslint-disable-next-line no-console
        console.warn(`[sequentialNumber] collision on ${candidate} (attempt ${attempt + 1}/${maxAttempts}), retrying`);
        continue;
      }
      throw err;
    }
  }
  throw lastErr || new Error('Failed to allocate a unique sequential number');
}
